const colors={data:'#526444',control:'#8C692F',config:'#7D8A6C',telemetry:'#526444'};
function rounded(points,r=22){let out=[points[0]];for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1],ab=Math.hypot(b[0]-a[0],b[1]-a[1]),bc=Math.hypot(c[0]-b[0],c[1]-b[1]);if(!ab||!bc)continue;const rr=Math.min(r,ab/2,bc/2),p=[b[0]+(a[0]-b[0])*rr/ab,b[1]+(a[1]-b[1])*rr/ab],q=[b[0]+(c[0]-b[0])*rr/bc,b[1]+(c[1]-b[1])*rr/bc];out.push(p);for(let j=1;j<=10;j++){const t=j/10,u=1-t;out.push([u*u*p[0]+2*u*t*b[0]+t*t*q[0],u*u*p[1]+2*u*t*b[1]+t*t*q[1]])}}out.push(points.at(-1));return out;}
function measure(points){const lengths=[0];for(let i=1;i<points.length;i++)lengths.push(lengths.at(-1)+Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]));return lengths;}
function at(points,lengths,t){const total=lengths.at(-1);t=Math.max(0,Math.min(total,t));let i=1;while(i<lengths.length-1&&lengths[i]<t)i++;const a=points[i-1],b=points[i],u=(t-lengths[i-1])/Math.max(.001,lengths[i]-lengths[i-1]);return{x:a[0]+(b[0]-a[0])*u,y:a[1]+(b[1]-a[1])*u,angle:Math.atan2(b[1]-a[1],b[0]-a[0])};}
export class Edges{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.paths=new Map();this.markers=[];this.terminators=[];this.projected=new Map();this.mask=null;}
 resize(w,h){this.w=w;this.h=h;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(w*this.dpr);this.canvas.height=Math.round(h*this.dpr);}
 render(model,engine,state,geometry=true){const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.w,this.h);this.paths.clear();this.markers=[];this.terminators=[];this.verdicts=[];let particleIndex=0;const nodeMap=new Map(model.nodes.map(n=>[n.id,n]));
 if(geometry||this.model!==model){this.model=model;this.projected.clear();this.mask=new Path2D();for(const n of model.nodes){const p=n.position,h=(state.heights?.[n.id]??n.height)+5+(state.lifts?.[n.id]||0);const corners=[];for(const y of[4,h])for(const[x,z]of[[-1,-1],[1,-1],[1,1],[-1,1]])corners.push(engine.project(p.x+x*p.width/2,y,p.z+z*p.depth/2));const hull=convex(corners);hull.forEach((q,i)=>i?this.mask.lineTo(...q):this.mask.moveTo(...q));this.mask.closePath();}}
 const ordered=[...model.edges].sort((a,b)=>Number(a.primary)-Number(b.primary)||Number(state.focusEdges?.has(a.id)||state.hoverEdge===a.id)-Number(state.focusEdges?.has(b.id)||state.hoverEdge===b.id));
 for(const e of ordered){let cached=this.projected.get(e.id);if(!cached){const pts=rounded(e.route).map(p=>engine.project(p[0],4,p[1])),a=nodeMap.get(e.from),b=nodeMap.get(e.to);if(e.sourcePort)pts.unshift(engine.project(e.sourcePort[0],(state.heights?.[a.id]??a.height)+5+(state.lifts?.[a.id]||0),e.sourcePort[1]));if(e.targetPort)pts.push(engine.project(e.targetPort[0],(state.heights?.[b.id]??b.height)+5+(state.lifts?.[b.id]||0),e.targetPort[1]));cached={pts,cum:measure(pts)};this.projected.set(e.id,cached)}const{pts,cum}=cached,length=cum.at(-1),end=e.blocked?length*.56:length;const focus=state.focusEdges?.has(e.id)||state.hoverEdge===e.id||(state.edgeFlashes?.[e.id]||0)>performance.now(),dim=state.focusEdges&&!focus;const dead=state.blastState.offline.includes(e.from)||state.blastState.starved.includes(e.from);const alpha=(dim?.10:focus?1:e.primary?.9:e.blocked?.7:.32)*(state.opacity?.[e.id]??1);const color=e.blocked?'#9D4B3B':focus||e.primary?'#526444':'#B1BAA5';c.strokeStyle=color;c.globalAlpha=alpha;c.lineWidth=focus?2.3:e.primary?1.7:1;c.lineCap='round';c.lineJoin='round';c.setLineDash(e.inferred?[2,3]:focus?[4,4]:[]);c.lineDashOffset=focus&&!state.reduced?-state.flowTime*12:0;c.beginPath();c.moveTo(...pts[0]);for(let i=1;i<pts.length;i++){if(cum[i]>=end){let p=at(pts,cum,end);c.lineTo(p.x,p.y);break}c.lineTo(...pts[i])}c.save();c.strokeStyle='#F5F2EB';c.globalAlpha=focus||e.primary?.92:.62;c.lineWidth=focus?5:3.5;c.setLineDash([]);c.stroke();c.restore();c.stroke();c.setLineDash([]);
 const arrow=at(pts,cum,end*.85);c.save();c.translate(arrow.x,arrow.y);c.rotate(arrow.angle);c.beginPath();c.moveTo(-4,-3);c.lineTo(0,0);c.lineTo(-4,3);c.stroke();c.restore();
 if(e.blocked){const p=at(pts,cum,end);c.strokeStyle='#9D4B3B';c.lineWidth=2;c.beginPath();c.moveTo(p.x-Math.sin(p.angle)*6,p.y+Math.cos(p.angle)*6);c.lineTo(p.x+Math.sin(p.angle)*6,p.y-Math.cos(p.angle)*6);c.stroke();this.terminators.push({id:e.id,x:p.x,y:p.y,label:e.short});}
 const edgeIndex=model.edges.indexOf(e),count=Math.floor((edgeIndex+1)*150/model.edges.length)-Math.floor(edgeIndex*150/model.edges.length);for(let j=0;j<count&&particleIndex<150;j++,particleIndex++){const phase=(particleIndex*.61803398875%1)*end;const travel=state.reduced?0:state.flowTime*38;const distance=(phase+travel)%Math.max(1,end);const p=at(pts,cum,distance);let fade=e.blocked?Math.min(1,(end-distance)/22):1;if(dead)fade*=.2;if(!e.primary&&!focus&&!e.blocked)fade*=.15;c.globalAlpha=alpha*fade;c.fillStyle=colors[e.kind];c.strokeStyle=colors[e.kind];const r=2.7;c.beginPath();if(e.kind==='control'){c.moveTo(p.x,p.y-r);c.lineTo(p.x+r,p.y);c.lineTo(p.x,p.y+r);c.lineTo(p.x-r,p.y);c.closePath();c.fill()}else if(e.kind==='config'){c.rect(p.x-r*.8,p.y-r*.8,r*1.6,r*1.6);c.fill()}else{c.arc(p.x,p.y,r,0,Math.PI*2);e.kind==='telemetry'?c.stroke():c.fill()}this.markers.push({edge:e.id,x:p.x,y:p.y});}
 const bound=model.nodes.filter(n=>n.id===e.from||n.id===e.to).flatMap(n=>n.checks||[]),failed=model.checks.filter(c=>bound.includes(c.id)&&['fail','error'].includes(c.status));
 const observations=e.id==='e-rcpt-int'?model.receiptContracts:[];
 if(observations.length||failed.length){const p=at(pts,cum,end*.67),fail=failed.length||observations.some(r=>r.status==='FAIL'),unavailable=observations.some(r=>r.status==='UNAVAILABLE');c.globalAlpha=1;c.strokeStyle=fail?'#9D4B3B':unavailable?'#8C692F':'#526444';c.lineWidth=3;c.beginPath();c.moveTo(p.x-7,p.y-5);c.lineTo(p.x+7,p.y+5);c.stroke();this.verdicts.push({id:e.id,x:p.x,y:p.y,fail,unavailable,label:observations.length?observations.map(r=>r.status+' · '+r.path.split('/').at(-1)).join(' / '):failed.map(c=>c.id+': '+c.status).join(' / '),detail:observations.map(r=>r.path+': '+(r.errors.join('; ')||r.reason||'No local preflight error')+' — '+r.scope).concat(failed.map(c=>c.firstFailure||c.status)).join('\n')});}
 this.paths.set(e.id,{pts,cum,length,end});}
 c.globalAlpha=1;c.setLineDash([]);c.lineDashOffset=0;c.save();c.globalCompositeOperation='destination-out';c.fill(this.mask);c.restore();
 for(const e of model.edges){if(!e.primary&&!state.focusEdges?.has(e.id)&&state.hoverEdge!==e.id)continue;const path=this.paths.get(e.id);if(!path)continue;const ends=e.blocked?[path.pts[0]]:[path.pts[0],path.pts.at(-1)];for(const p of ends){c.beginPath();c.arc(p[0],p[1],2.5,0,Math.PI*2);c.fillStyle='#F5F2EB';c.fill();c.strokeStyle=e.blocked?'#9D4B3B':'#526444';c.lineWidth=1.2;c.stroke();}}

 if(state.selected){const n=model.nodes.find(n=>n.id===state.selected);if(n){const p=n.position,h=state.heights?.[n.id]??n.height;const qs=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>engine.project(p.x+x*(p.width/2+8),h+6,p.z+z*(p.depth/2+8)));c.strokeStyle='#526444';c.lineWidth=2;c.beginPath();qs.forEach((q,i)=>i?c.lineTo(...q):c.moveTo(...q));c.closePath();c.stroke();}}
 }
 pick(x,y){let best=null,distance=6;for(const[id,path]of [...this.paths].reverse()){for(let i=1;i<path.pts.length;i++){if(path.cum[i-1]>path.end)break;const a=path.pts[i-1],cut=path.cum[i]>path.end?at(path.pts,path.cum,path.end):null,b=cut?[cut.x,cut.y]:path.pts[i],dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/Math.max(1,dx*dx+dy*dy))),d=Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy);if(d<distance){distance=d;best=id}}}return best;}

}

function convex(points){const p=[...points].sort((a,b)=>a[0]-b[0]||a[1]-b[1]),cross=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const lower=[],upper=[];for(const q of p){while(lower.length>1&&cross(lower.at(-2),lower.at(-1),q)<=0)lower.pop();lower.push(q)}for(const q of [...p].reverse()){while(upper.length>1&&cross(upper.at(-2),upper.at(-1),q)<=0)upper.pop();upper.push(q)}return lower.slice(0,-1).concat(upper.slice(0,-1))}
