/*! three.js — Copyright 2010-2026 three.js authors. MIT license; full notice retained in bundled dependency. */
import {WebGLRenderer,Scene,Color,PerspectiveCamera,OrthographicCamera,AmbientLight,DirectionalLight,Mesh,MeshStandardMaterial,MeshBasicMaterial,BoxGeometry,PlaneGeometry,Shape,ExtrudeGeometry,EdgesGeometry,LineSegments,LineBasicMaterial,LineDashedMaterial,BufferGeometry,Float32BufferAttribute,CanvasTexture,DoubleSide,Group,Raycaster,Vector2,Vector3,SRGBColorSpace} from 'three';
const C={paper:'#F5F2EB',paper2:'#F1F0E7',panel:'#ECEEE3',olive:'#526444',sage:'#81906F',line:'#B1BAA5',border:'#C3CABA',brick:'#9D4B3B',amber:'#8C692F',tested:'#3F6B3A'};
function texture(draw,size=128){const c=document.createElement('canvas');c.width=c.height=size;draw(c.getContext('2d'),size);const t=new CanvasTexture(c);t.colorSpace=SRGBColorSpace;return t;}
const icons={lock:c=>{c.strokeRect(30,52,68,52);c.beginPath();c.arc(64,49,23,Math.PI,0);c.stroke();c.beginPath();c.moveTo(64,70);c.lineTo(64,86);c.stroke()},doc:c=>{c.strokeRect(35,20,60,88);for(let y of [47,65,83]){c.beginPath();c.moveTo(47,y);c.lineTo(83,y);c.stroke()}},branch:c=>{c.beginPath();c.moveTo(35,25);c.lineTo(35,94);c.moveTo(35,60);c.bezierCurveTo(85,65,91,52,91,25);c.stroke();for(let [x,y]of[[35,23],[35,100],[91,23]]){c.beginPath();c.arc(x,y,8,0,7);c.stroke()}},person:c=>{c.beginPath();c.arc(64,37,20,0,7);c.stroke();c.beginPath();c.arc(64,99,32,Math.PI,0);c.stroke()},code:c=>{c.beginPath();c.moveTo(45,32);c.lineTo(18,64);c.lineTo(45,96);c.moveTo(83,32);c.lineTo(110,64);c.lineTo(83,96);c.moveTo(73,24);c.lineTo(55,104);c.stroke()},receipt:c=>{c.beginPath();c.moveTo(30,19);c.lineTo(98,19);c.lineTo(98,111);for(let x=98;x>=30;x-=17)c.lineTo(x,x%34?103:111);c.closePath();c.stroke();for(let y of[43,63,83]){c.beginPath();c.moveTo(44,y);c.lineTo(83,y);c.stroke()}},shield:c=>{c.beginPath();c.moveTo(64,17);c.lineTo(103,33);c.lineTo(96,76);c.quadraticCurveTo(90,97,64,112);c.quadraticCurveTo(38,97,32,76);c.lineTo(25,33);c.closePath();c.stroke();c.beginPath();c.moveTo(44,63);c.lineTo(58,77);c.lineTo(84,49);c.stroke()},flag:c=>{c.beginPath();c.moveTo(34,111);c.lineTo(34,19);c.lineTo(99,25);c.lineTo(82,46);c.lineTo(98,66);c.lineTo(34,60);c.stroke()},globe:c=>{c.beginPath();c.arc(64,64,43,0,7);c.stroke();c.beginPath();c.ellipse(64,64,20,43,0,0,7);c.moveTo(22,64);c.lineTo(106,64);c.stroke()}};
export function create3D(canvas,model){let context=null;try{context=canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'low-power'});}catch{}if(!context)return null;return new Engine3D(canvas,model,context);}
export class Engine3D{
 constructor(canvas,model,context){this.kind='webgl2';this.canvas=canvas;this.model=model;this.width=1;this.height=1;this.renderer=new WebGLRenderer({canvas,context,antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setClearColor(C.paper);this.renderer.outputColorSpace=SRGBColorSpace;this.scene=new Scene();this.scene.add(new AmbientLight(0xffffff,1.8));const sun=new DirectionalLight(0xffffff,1.6);sun.position.set(-1200,2000,900);this.scene.add(sun);this.perspective=new PerspectiveCamera(28,1,.1,50000);this.ortho=new OrthographicCamera(-1,1,1,-1,.1,50000);this.active=this.perspective;this.raycaster=new Raycaster();this.pointer=new Vector2();this.vector=new Vector3();this.groups=new Map();this.pickables=[];this.assets=[];
 this.shadow=texture((c,s)=>{let g=c.createRadialGradient(s/2,s/2,5,s/2,s/2,s/2);g.addColorStop(0,'rgba(48,55,41,.26)');g.addColorStop(.5,'rgba(48,55,41,.1)');g.addColorStop(1,'rgba(48,55,41,0)');c.fillStyle=g;c.fillRect(0,0,s,s)});
 this.hatch=texture((c,s)=>{c.strokeStyle='#81906F';c.lineWidth=2;for(let x=-s;x<s*2;x+=14){c.beginPath();c.moveTo(x,0);c.lineTo(x+s,s);c.stroke()}});
 this.iconTextures={};for(const [name,draw]of Object.entries(icons))this.iconTextures[name]=texture(c=>{c.strokeStyle=C.olive;c.lineWidth=5;c.lineCap='round';c.lineJoin='round';draw(c)});
 this.portTexture=texture(c=>{c.strokeStyle=C.olive;c.lineWidth=5;c.beginPath();c.arc(64,64,30,0,7);c.stroke();c.beginPath();c.moveTo(64,22);c.lineTo(64,106);c.moveTo(48,90);c.lineTo(64,106);c.lineTo(80,90);c.stroke()});this.seal=texture(c=>{c.strokeStyle=C.tested;c.lineWidth=7;c.beginPath();c.arc(64,64,42,0,7);c.stroke();c.beginPath();c.moveTo(40,63);c.lineTo(57,82);c.lineTo(89,45);c.stroke()});this.content=new Group();this.scene.add(this.content);this.build();}
 resize(w,h){this.width=w;this.height=h;this.renderer.setSize(w,h,false);}
 plane(w,d,material,x,y,z){const m=new Mesh(new PlaneGeometry(w,d),material);m.rotation.x=-Math.PI/2;m.position.set(x,y,z);return m;}
 build(){for(const obj of this.assets){obj.geometry?.dispose();if(Array.isArray(obj.material))obj.material.forEach(m=>m.dispose());else obj.material?.dispose()}this.assets=[];this.content.clear();this.groups.clear();this.pickables=[];const m=this.model,b=m.layout.bounds;const track=o=>{this.assets.push(o);return o};
 const points=[];for(let x=Math.floor(b.x0/37.5)*37.5;x<=b.x1;x+=37.5)points.push(x,0,b.z0,x,0,b.z1);for(let z=Math.floor(b.z0/37.5)*37.5;z<=b.z1;z+=37.5)points.push(b.x0,0,z,b.x1,0,z);const grid=new BufferGeometry();grid.setAttribute('position',new Float32BufferAttribute(points,3));this.content.add(track(new LineSegments(grid,new LineBasicMaterial({color:'#D9DBCE',transparent:true,opacity:.16}))));
 for(const zone of m.zones){const p=zone.plate,w=p.x1-p.x0,d=p.z1-p.z0,mesh=track(new Mesh(new BoxGeometry(w,2.5,d),new MeshBasicMaterial({color:'#E8ECDF',transparent:true,opacity:.42,depthWrite:false})));mesh.position.set((p.x0+p.x1)/2,1.25,(p.z0+p.z1)/2);this.content.add(mesh);const rim=track(new LineSegments(new EdgesGeometry(new BoxGeometry(w,.2,d)),new LineBasicMaterial({color:C.border,transparent:true,opacity:.8})));rim.position.copy(mesh.position);rim.position.y=2.6;this.content.add(rim)}
 for(const n of m.nodes){const p=n.position,w=p.width,d=p.depth;const group=new Group();group.position.set(p.x,4,p.z);this.content.add(group);const shadow=track(this.plane(w*1.6,d*2.1,new MeshBasicMaterial({map:this.shadow,transparent:true,depthWrite:false}),p.x,2.7,p.z+10));this.content.add(shadow);if(n.primary){const plate=track(new Mesh(new BoxGeometry(w+15,1,d+15),new MeshBasicMaterial({color:C.olive,transparent:true,opacity:.2})));plate.position.y=-.5;group.add(plate)}
 const geo=new BoxGeometry(w,1,d);geo.translate(0,.5,0);const material=new MeshBasicMaterial({color:C.paper2,transparent:true,opacity:1});const side=new MeshBasicMaterial({color:'#CED6C3',transparent:true,opacity:1});const body=track(new Mesh(geo,[side,side,material,side,side,side]));body.visible=n.maturity!=='planned';group.add(body);
 const dashed=n.inferred||n.maturity==='planned';const outline=track(new LineSegments(new EdgesGeometry(new BoxGeometry(w,1,d)),dashed?new LineDashedMaterial({color:C.line,dashSize:6,gapSize:4,transparent:true}):new LineBasicMaterial({color:C.border,transparent:true})));outline.computeLineDistances();group.add(outline);
 const pick=track(new Mesh(new BoxGeometry(w,1,d),new MeshBasicMaterial({visible:false})));pick.userData.id=n.id;group.add(pick);this.pickables.push(pick);
 const tier=m.tiers.find(t=>t.id===n.tier);const icon=track(this.plane(38,38,new MeshBasicMaterial({map:this.iconTextures[tier.icon],transparent:true,depthWrite:false,side:DoubleSide}),-w/2+31,1,0));group.add(icon);
 const port=track(this.plane(12,12,new MeshBasicMaterial({map:this.portTexture,transparent:true,depthWrite:false}),0,1,d/2-8));group.add(port);
 const top=track(this.plane(w-8,d-8,new MeshBasicMaterial({map:this.hatch,transparent:true,opacity:.18,depthWrite:false}),0,1,0));top.visible=n.maturity==='stub';group.add(top);
 const seal=track(this.plane(22,22,new MeshBasicMaterial({map:this.seal,transparent:true,depthWrite:false}),w/2-20,1,-d/2+17));seal.visible=n.maturity==='tested';group.add(seal);
 const column=track(new Mesh(new BoxGeometry(w+8,60,d+8),new MeshBasicMaterial({color:C.olive,transparent:true,opacity:.045,depthWrite:false})));column.position.y=30;column.visible=false;group.add(column);
 const inset=track(this.plane(w-20,3,new MeshBasicMaterial({color:n.maturity==='tested'?C.tested:n.primary?C.olive:C.line,transparent:true,opacity:.6,depthWrite:false}),0,1,-d/2+10));group.add(inset);
 this.groups.set(n.id,{group,side,inset,body,outline,pick,icon,port,top,seal,column,material,shadow});}
 }
 update(model){const old=this.model;this.model=model;const structural=old.layout.topology!==model.layout.topology||old.nodes.some(n=>model.nodes.find(x=>x.id===n.id)?.maturity!==n.maturity);if(structural)this.build();}
 render(state){const b=this.model.layout.bounds,c=state.camera,top=state.width<900?92:62,bottom=state.sheet+62;const dx=b.x1-b.x0,dz=b.z1-b.z0;const xx=Math.abs(dx*Math.cos(c.yaw))+Math.abs(dz*Math.sin(c.yaw)),zz=Math.abs(dz*Math.cos(c.yaw))+Math.abs(dx*Math.sin(c.yaw));this.scale=Math.min((this.width-75)/xx,(this.height-top-bottom)/(zz*Math.sin(c.pitch)+80))*(c.zoom/state.baseZoom);this.scale=Math.max(.02,this.scale);const cx=(b.x0+b.x1)/2+c.panX,cz=(b.z0+b.z1)/2+c.panZ,worldH=this.height/this.scale;const dist=(worldH/2)/Math.tan(14*Math.PI/180);this.active=c.plan?this.ortho:this.perspective;this.active.near=Math.max(1,dist*.05);this.active.far=dist*4+5000;
 if(c.plan){this.ortho.left=-this.width/this.scale/2;this.ortho.right=-this.ortho.left;this.ortho.top=worldH/2;this.ortho.bottom=-worldH/2}else this.perspective.aspect=this.width/this.height;
 this.active.position.set(cx+Math.sin(c.yaw)*dist*Math.cos(c.pitch),dist*Math.sin(c.pitch),cz+Math.cos(c.yaw)*dist*Math.cos(c.pitch));if(c.plan)this.active.up.set(Math.sin(c.yaw),0,-Math.cos(c.yaw));else this.active.up.set(0,1,0);this.active.lookAt(cx,0,cz);this.active.setViewOffset(this.width,this.height,0,(bottom-top)/2,this.width,this.height);this.active.updateProjectionMatrix();this.active.updateMatrixWorld();
 for(const n of this.model.nodes){const a=this.groups.get(n.id);if(!a)continue;const h=state.heights?.[n.id]??n.height,off=state.blastState.offline.includes(n.id),starved=state.blastState.starved.includes(n.id),dim=state.focusNodes&&!state.focusNodes.has(n.id),lift=state.lifts?.[n.id]||0;a.group.position.x=n.position.x;a.group.position.z=n.position.z;a.group.position.y=4+lift+(n.maturity==='planned'?2:0);a.body.scale.y=h;a.outline.scale.y=h;a.outline.position.y=h/2;a.pick.scale.y=h;a.pick.position.y=h/2;a.top.position.y=h+.2;a.inset.position.y=h+.4;for(const obj of[a.icon,a.port,a.seal])obj.position.y=h+1.2;a.material.color.set(off?'#EAD6CE':starved?'#ECE0C7':n.id===state.selected?'#E1E8D4':n.id===state.hover?'#EBEEDC':C.paper2);a.side.color.set(off?'#C49A8D':starved?'#CAB78D':'#CED6C3');a.material.opacity=dim?.28:n.maturity==='stub'?.82:1;a.side.opacity=a.material.opacity;a.outline.material.opacity=dim?.25:1;a.outline.material.color.set(off?C.brick:starved?C.amber:n.id===state.selected?C.olive:C.line);a.column.visible=n.id===state.selected;a.icon.material.opacity=dim?.2:1;a.shadow.material.opacity=dim?.3:1;const fade=state.opacity?.[n.id]??1;for(const obj of a.group.children){if(!obj.material)continue;if(Array.isArray(obj.material)){[...new Set(obj.material)].forEach(m=>m.opacity*=fade);continue}if([a.body,a.outline,a.icon].includes(obj))obj.material.opacity*=fade;else{obj.userData.baseOpacity??=obj.material.opacity;obj.material.opacity=obj.userData.baseOpacity*fade*(dim?.3:1)}}a.shadow.material.opacity*=fade;}
 this.renderer.render(this.scene,this.active);}
 project(x,y,z){const p=this.vector.set(x,y,z).project(this.active);return[(p.x+1)*this.width/2,(1-p.y)*this.height/2];}
 pick(x,y){this.pointer.set(x/this.width*2-1,1-y/this.height*2);this.raycaster.setFromCamera(this.pointer,this.active);return this.raycaster.intersectObjects(this.pickables,false)[0]?.object.userData.id||null;}
 matrix(){return [...this.active.matrixWorld.elements,...this.active.projectionMatrix.elements];}
 dispose(){this.renderer.dispose();}
}
