const palette={paper:'#F5F2EB',panel:'#ECEEE3',line:'#B1BAA5',ink:'#303729',olive:'#526444',brick:'#9D4B3B',amber:'#8C692F'};
export class Engine2D{
 constructor(canvas,model){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.model=model;this.kind='canvas2d';this.width=1;this.height=1;this.scale=1;this.cam={};this.boxes=[];this.cells=new Map();}
 resize(w,h){this.width=w;this.height=h;this.dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(w*this.dpr);this.canvas.height=Math.round(h*this.dpr);}
 update(model){this.model=model;}
 project(x,y,z){const c=this.cam,b=this.model.layout.bounds,cx=(b.x0+b.x1)/2+c.panX,cz=(b.z0+b.z1)/2+c.panZ,dx=x-cx,dz=z-cz;const xx=dx*Math.cos(c.yaw)-dz*Math.sin(c.yaw),zz=dx*Math.sin(c.yaw)+dz*Math.cos(c.yaw);return [this.width/2+xx*this.scale,this.top+(this.height-this.top-this.bottom)/2+(zz*Math.sin(c.pitch)-y*Math.cos(c.pitch))*this.scale];}
 render(state){this.cam=state.camera;this.top=state.width<900?92:68;this.bottom=state.sheet+64;const b=this.model.layout.bounds;this.scale=Math.min((this.width-55)/(b.x1-b.x0),(this.height-this.top-this.bottom)/(b.z1-b.z0))*(this.cam.zoom/state.baseZoom);const ctx=this.ctx,d=this.dpr;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,this.width,this.height);ctx.fillStyle=palette.paper;ctx.fillRect(0,0,this.width,this.height);const polygon=(pts,fill,stroke,dash=[])=>{ctx.beginPath();pts.forEach((p,i)=>{const q=this.project(...p);i?ctx.lineTo(...q):ctx.moveTo(...q)});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([])}};
 ctx.strokeStyle='#D9DBCE';ctx.lineWidth=.6;for(let x=Math.floor(b.x0/150)*150;x<b.x1;x+=150){ctx.beginPath();ctx.moveTo(...this.project(x,0,b.z0));ctx.lineTo(...this.project(x,0,b.z1));ctx.stroke()}for(let z=Math.floor(b.z0/150)*150;z<b.z1;z+=150){ctx.beginPath();ctx.moveTo(...this.project(b.x0,0,z));ctx.lineTo(...this.project(b.x1,0,z));ctx.stroke()}
 for(const zone of this.model.zones){const p=zone.plate;polygon([[p.x0,2,p.z0],[p.x1,2,p.z0],[p.x1,2,p.z1],[p.x0,2,p.z1]],'#ECEEE3CC','#C3CABA')}
 this.boxes=[];this.cells.clear();for(const n of [...this.model.nodes].sort((a,b)=>a.position.z-b.position.z)){const p=n.position,w=p.width/2,l=p.depth/2,h=state.heights?.[n.id]??n.height,off=state.blastState.offline.includes(n.id),starved=state.blastState.starved.includes(n.id),planned=n.maturity==='planned';ctx.globalAlpha=(state.opacity?.[n.id]??1)*(state.focusNodes&&!state.focusNodes.has(n.id)?.3:1);const y=4+(planned?2:0);const top=[[p.x-w,y+h,p.z-l],[p.x+w,y+h,p.z-l],[p.x+w,y+h,p.z+l],[p.x-w,y+h,p.z+l]];polygon([[p.x-w,y,p.z+l],[p.x+w,y,p.z+l],top[2],top[3]],planned?null:'#DDE2D2',palette.line,planned?[3,3]:[]);polygon([[p.x+w,y,p.z-l],[p.x+w,y,p.z+l],top[2],top[1]],planned?null:'#D2D9C6',palette.line,planned?[3,3]:[]);polygon(top,planned?null:off?'#E6CFC4':starved?'#EAE0C5':'#F1F0E7',state.selected===n.id?palette.olive:palette.line,n.inferred||planned?[3,3]:[]);const coords=top.map(q=>this.project(...q));this.boxes.push({id:n.id,x0:Math.min(...coords.map(q=>q[0]))-5,x1:Math.max(...coords.map(q=>q[0]))+5,y0:Math.min(...coords.map(q=>q[1]))-5,y1:Math.max(...coords.map(q=>q[1]))+15});}
 ctx.globalAlpha=1;for(const b of this.boxes)for(let x=Math.floor(b.x0/64);x<=Math.floor(b.x1/64);x++)for(let y=Math.floor(b.y0/64);y<=Math.floor(b.y1/64);y++){const key=x+","+y;if(!this.cells.has(key))this.cells.set(key,[]);this.cells.get(key).push(b)}
 }
 pick(x,y){return (this.cells.get(Math.floor(x/64)+","+Math.floor(y/64))||[]).findLast(b=>x>=b.x0&&x<=b.x1&&y>=b.y0&&y<=b.y1)?.id||null;}
 matrix(){return [this.cam.yaw,this.cam.pitch,this.cam.zoom,this.cam.panX,this.cam.panZ,this.width,this.height];}
 dispose(){}
}
