export function overlaps(a,b,pad=2){return a.x0<b.x1+pad&&a.x1>b.x0-pad&&a.y0<b.y1+pad&&a.y1>b.y0-pad;}
export class Labels{
 constructor(container,leaders,onSelect){this.container=container;this.leaders=leaders;this.onSelect=onSelect;this.elements=new Map();this.zoneElements=new Map();this.blockElements=new Map();this.visible=[];this.blocked=[];this.zones=[];this.verdictElements=new Map();}
 sync(model){for(const[id,el]of this.elements)if(!model.nodes.some(n=>n.id===id)){el.remove();this.elements.delete(id)}for(const n of model.nodes)if(!this.elements.has(n.id)){const el=document.createElement('button');el.className='node-label';el.dataset.node=n.id;el.setAttribute('aria-hidden','true');el.tabIndex=-1;el.addEventListener('click',e=>{e.stopPropagation();this.onSelect(n.id)});this.container.append(el);this.elements.set(n.id,el)}for(const z of model.zones)if(!this.zoneElements.has(z.id)){const el=document.createElement('div');el.className='zone-label bracket';el.textContent=z.label;this.container.append(el);this.zoneElements.set(z.id,el)}for(const e of model.edges.filter(e=>e.blocked))if(!this.blockElements.has(e.id)){const el=document.createElement('div');el.className='block-label bracket';el.textContent=e.short;this.container.append(el);this.blockElements.set(e.id,el)}this.dirty=true;}
 render(model,engine,edges,state){const w=engine.width,h=engine.height,short=state.camera.zoom<.8||state.width<=1180,placed=[],lines=[];this.visible=[];this.blocked=[];this.zones=[];
 const scene=this.container.getBoundingClientRect();for(const el of document.querySelectorAll('#scene .hud')){if(el.hidden||getComputedStyle(el).display==='none')continue;const r=el.getBoundingClientRect();placed.push({x0:r.left-scene.left,y0:r.top-scene.top,x1:r.right-scene.left,y1:r.bottom-scene.top})}if(state.sheet)placed.push({x0:0,y0:h-state.sheet,x1:w,y1:h});
 const fits=r=>r.x0>=6&&r.y0>=6&&r.x1<=w-6&&r.y1<=h-86-state.sheet&&!placed.some(a=>overlaps(a,r,3));
 const rect=(x,y,ww,hh)=>({x0:x,y0:y,x1:x+ww,y1:y+hh});const position=(el,r)=>{el.style.left=r.x0+'px';el.style.top=r.y0+'px';el.hidden=false};
 for(const z of model.zones){const el=this.zoneElements.get(z.id),p=z.plate,q=engine.project(p.x0+8,4,p.z0+13);const r=rect(q[0],q[1],el.offsetWidth||100,14);if(fits(r)){position(el,r);placed.push(r);this.zones.push({id:z.id,...r})}else el.hidden=true;}
 for(const t of edges.terminators){const el=this.blockElements.get(t.id);el.hidden=false;const ww=el.offsetWidth,hh=el.offsetHeight;let candidates=[[t.x+10,t.y-hh/2],[t.x-ww-10,t.y-hh/2],[t.x-ww/2,t.y-hh-12],[t.x-ww/2,t.y+12]];for(let y of[96,128,h-118-state.sheet,h-86-state.sheet])candidates.push([16,y],[w-ww-16,y]);const r=candidates.map(p=>rect(...p,ww,hh)).find(fits);if(r){position(el,r);placed.push(r);this.blocked.push({id:t.id,...r});lines.push([t.x,t.y,Math.max(r.x0,Math.min(r.x1,t.x)),Math.max(r.y0,Math.min(r.y1,t.y))])}else el.hidden=true;}
 for(const[id,el]of this.verdictElements)el.hidden=true;
 for(const v of edges.verdicts||[]){let el=this.verdictElements.get(v.id);if(!el){el=document.createElement('button');el.className='receipt-verdict';el.dataset.edge=v.id;this.container.append(el);this.verdictElements.set(v.id,el)}el.textContent=v.label;el.title=v.detail;el.classList.toggle('failure',!!v.fail);el.classList.toggle('unavailable',!!v.unavailable&&!v.fail);el.hidden=false;const ww=el.offsetWidth,hh=el.offsetHeight,r=[[v.x+12,v.y-hh/2],[v.x-ww-12,v.y-hh/2],[16,h-145-state.sheet]].map(p=>rect(...p,ww,hh)).find(fits);if(r){position(el,r);placed.push(r);lines.push([v.x,v.y,r.x0,r.y0+hh/2])}else el.hidden=true;}
 const ordered=[...model.nodes].sort((a,b)=>(b.id===state.selected)-(a.id===state.selected)||Number(b.primary)-Number(a.primary)||a.position.rank-b.position.rank||a.id.localeCompare(b.id));
 // Batch DOM writes, then geometry reads, to avoid layout thrashing each frame.
 for(const n of ordered){const el=this.elements.get(n.id),title=short?n.short:n.title;if(el.dataset.title!==title){el.textContent=title;el.dataset.title=title;this.dirty=true}const tag=state.tags?.[n.id];let badge=el.querySelector('.change-tag');if(tag&&tag.until>performance.now()){if(!badge){badge=document.createElement('span');badge.className='change-tag';el.append(badge)}badge.textContent=tag.text}else if(badge)badge.remove();el.hidden=false;el.style.maxWidth=(short?112:144)+'px';el.classList.toggle('dim',!!state.focusNodes&&!state.focusNodes.has(n.id));el.style.opacity=state.opacity?.[n.id]??'';el.classList.toggle('selected',state.selected===n.id);el.classList.toggle('hovered',state.hover===n.id);el.classList.toggle('pulse',(state.pulses?.[n.id]||0)>performance.now());}
 const sizes=new Map(ordered.map(n=>{const el=this.elements.get(n.id);return[n.id,[el.offsetWidth,el.offsetHeight]]}));
 for(const n of ordered){const el=this.elements.get(n.id),p=n.position,height=state.heights?.[n.id]??n.height,q=engine.project(p.x,height+6+(state.lifts?.[n.id]||0),p.z);const[ww,hh]=sizes.get(n.id);const fp=[[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>engine.project(p.x+x*p.width/2,height+6,p.z+z*p.depth/2));const xs=fp.map(p=>p[0]),ys=fp.map(p=>p[1]),x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys);const gap=5;
 const candidates=[[q[0]-ww/2,y1+gap],[q[0]-ww/2,y0-hh-gap],[q[0]-ww/2,q[1]-hh/2],[x0-ww-gap,q[1]-hh/2],[x1+gap,q[1]-hh/2],[x0-ww/2,y1+gap],[x1-ww/2,y1+gap],[x0-ww/2,y0-hh-gap],[x1-ww/2,y0-hh-gap],[q[0]-ww/2,y1+hh+10],[q[0]-ww/2,y0-hh*2-10],[x0-ww-42,y1+hh+16],[x1+42,y0-hh*2-16]];
 const r=candidates.map(p=>rect(...p,ww,hh)).find(fits);
 if(r&&state.camera.zoom>=.5){position(el,r);placed.push(r);this.visible.push({id:n.id,...r});const lx=Math.max(r.x0,Math.min(r.x1,q[0])),ly=Math.max(r.y0,Math.min(r.y1,q[1]));if(Math.hypot(lx-q[0],ly-q[1])>18)lines.push([q[0],q[1],lx,ly]);}else el.hidden=true;
 }
 this.leaders.innerHTML=lines.map(([x,y,a,b])=>`<path d="M${x.toFixed(1)},${y.toFixed(1)} L${a.toFixed(1)},${b.toFixed(1)}" fill="none" stroke="#B1BAA5" stroke-width=".65" opacity=".6"/>`).join('');
 }
}
