import {$} from './ui.js';
export function connectLive({get,applyPatch,refresh,ui}){
 const boot=window.__ARCHMAP_LIVE__;if(!boot||location.protocol==='file:')return;
 let stream=null,delay=1000,retry=null,token=boot.token,stopped=false,probing=false,connectedSession=boot.session;
 const status=value=>{const old=get().state.live;get().state.live=value;if(old==='snapshot')refresh();else ui.metadata()};
 const observation=data=>{Object.assign(get().state,{lastScan:data.lastScan,checking:!!data.checking,syncState:data.pending?'pending':'current',syncError:data.error||null});ui.metadata()};
 async function reconcile(){const r=await fetch('/api/model',{cache:'no-store'});if(!r.ok)throw Error('Model unavailable');const model=await r.json();if(model.meta.rev!==get().model.meta.rev||model.meta.generated!==get().model.meta.generated)applyPatch({model,changes:[],trigger:[],at:model.meta.generated});}
 function reconnect(){stream?.close();stream=null;if(stopped)return;status('reconnecting');clearTimeout(retry);retry=setTimeout(start,delay);delay=Math.min(10000,delay*2);}
 async function health(){const response=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)throw Error('Health unavailable');return response.json();}
 async function start(){if(stopped)return;try{const h=await health();token=h.token;connectedSession=h.session;get().state.checking=h.checking;if(h.watch)observation(h.watch);await reconcile();stream?.close();stream=new EventSource('/events');stream.addEventListener('connected',async event=>{try{const data=JSON.parse(event.data);if(data.session!==connectedSession||data.rev!==get().model.meta.rev)await reconcile();delay=1000;status('live')}catch{reconnect()}});stream.addEventListener('model-patch',event=>{const patch=JSON.parse(event.data);if(patch.rev>get().model.meta.rev)applyPatch(patch);get().state.syncState='current';status('live')});stream.addEventListener('watch-status',event=>observation(JSON.parse(event.data)));stream.addEventListener('reconcile',()=>reconcile().catch(reconnect));stream.addEventListener('checks-started',()=>{get().state.checking=true;ui.render()});stream.addEventListener('checks-finished',()=>{get().state.checking=false;ui.render()});stream.addEventListener('model-error',event=>{const message=JSON.parse(event.data).message;get().state.syncError=message;ui.metadata();ui.announce(message)});stream.onerror=reconnect;}catch{reconnect()}}
 // A modest independent probe detects a stalled stream and missed updates.
 const watchdog=setInterval(async()=>{if(stopped||probing||get().state.live!=='live')return;probing=true;try{const h=await health();if(h.session!==connectedSession){reconnect();return}if(h.watch)observation(h.watch);if(h.rev!==get().model.meta.rev)await reconcile()}catch{reconnect()}finally{probing=false}},15000);
 $('run-checks').onclick=async()=>{try{const response=await fetch('/api/run-checks',{method:'POST',headers:{'X-Archmap-Token':token}});if(!response.ok)throw Error('Checks rejected');get().state.checking=true;ui.render()}catch{reconnect()}};
 window.addEventListener('pagehide',()=>{stopped=true;clearTimeout(retry);clearInterval(watchdog);stream?.close()});start();
}
