import {create3D} from './engine3d.js';
import {Engine2D} from './engine2d.js';
import {Edges} from './edges.js';
import {Labels,overlaps} from './labels.js';
import {UI,$,blast,trace} from './ui.js';
import {connectLive} from './live.js';
let model=window.__ARCHMAP_MODEL__,renderModel=model;delete window.__ARCHMAP_MODEL__;
const scene=$('scene');let canvas=$('board');const reduced=matchMedia('(prefers-reduced-motion: reduce)');let preferences={};try{preferences=JSON.parse(localStorage.getItem('archmap-preferences')||'{}')}catch{}
const initialCamera=()=>({yaw:innerWidth<=600?0:-5*Math.PI/180,pitch:innerWidth<=600?Math.PI/2:61*Math.PI/180,zoom:innerWidth<=600?.7:1,panX:0,panZ:0,plan:innerWidth<=600});
const state={width:innerWidth,camera:initialCamera(),baseZoom:innerWidth<=600?.7:1,sheet:0,collapsed:preferences.collapsed??innerWidth<=1080,tab:preferences.tab==='how'?'how':'what',flow:true,flowTime:0,rotate:false,reduced:reduced.matches,selected:null,payload:null,hover:null,hoverEdge:null,tour:-1,trace:null,blast:false,blastState:blast(model),focusNodes:null,focusEdges:null,heights:{},lifts:{},pulses:{},tags:{},opacity:{},edgeFlashes:{},changes:[],live:'snapshot',lastScan:null,syncState:'snapshot',syncError:null,checking:false,frameCount:0,frameTimes:[],keyboardNode:null};
let engine=new Engine2D(canvas,model);
const edges=new Edges($('edges')),labels=new Labels($('labels'),$('leaders'),id=>select(id));labels.sync(model);
let dirty=true,raf=0,last=0,tween=null,heightTweens={},liftTweens={},positionTweens={},opacityTweens={},minimapBounds=null;
function save(){try{localStorage.setItem('archmap-preferences',JSON.stringify({collapsed:state.collapsed,tab:state.tab}))}catch{}}
function invalidate(){dirty=true;if(!document.hidden&&!raf)raf=requestAnimationFrame(frame);}
function moving(){return(state.flow&&!state.reduced)||state.rotate||tween||Object.keys(heightTweens).length||Object.keys(liftTweens).length||Object.keys(positionTweens).length||Object.keys(opacityTweens).length;}
function cameraTo(to,duration=520){state.rotate=false;if(state.reduced||!duration){Object.assign(state.camera,to);tween=null}else tween={from:{...state.camera},to:{...state.camera,...to},at:performance.now(),duration};invalidate();}
function frame(time){raf=0;if(document.hidden){last=0;return}const dt=last?Math.min((time-last)/1000,.05):0;last=time;const start=performance.now();let geometry=dirty;dirty=false;if(state.flow&&!state.reduced)state.flowTime+=dt;if(state.rotate&&!state.reduced){state.camera.yaw+=dt*.12;if(state.camera.yaw>Math.PI/3)state.camera.yaw=-Math.PI/3;geometry=true}if(tween){const t=Math.min(1,(time-tween.at)/tween.duration),e=1-(1-t)**3;for(const k of['yaw','pitch','zoom','panX','panZ'])state.camera[k]=tween.from[k]+(tween.to[k]-tween.from[k])*e;state.camera.plan=tween.to.plan;geometry=true;if(t===1)tween=null}for(const[ids,target,property]of[[heightTweens,state.heights,'height'],[liftTweens,state.lifts,'lift']])for(const[id,t]of Object.entries(ids)){const p=t.duration?Math.min(1,(time-t.at)/t.duration):1;target[id]=t.from+(t.to-t.from)*(1-(1-p)**3);geometry=true;if(p===1)delete ids[id]}
 for(const[id,t]of Object.entries(positionTweens)){const n=model.nodes.find(n=>n.id===id),p=Math.min(1,(time-t.at)/520),e=1-(1-p)**3;if(n){n.position.x=t.from.x+(t.to.x-t.from.x)*e;n.position.z=t.from.z+(t.to.z-t.from.z)*e}geometry=true;if(p===1)delete positionTweens[id]}
 let purge=false;for(const[id,t]of Object.entries(opacityTweens)){const p=Math.min(1,(time-t.at)/300);state.opacity[id]=t.from+(t.to-t.from)*p;geometry=true;if(p===1){delete opacityTweens[id];if(t.to===0)purge=true}}
 if(purge){renderModel={...model,nodes:renderModel.nodes.filter(n=>state.opacity[n.id]!==0||model.nodes.some(x=>x.id===n.id)),edges:renderModel.edges.filter(e=>state.opacity[e.id]!==0||model.edges.some(x=>x.id===e.id))};engine.update(renderModel);labels.sync(renderModel);}
 if(geometry){engine.render(state);minimap();}edges.render(renderModel,engine,state,geometry);if(geometry)labels.render(renderModel,engine,edges,state);$('zoom-readout').textContent=state.camera.zoom.toFixed(2).replace(/0$/,'')+'×';state.frameCount++;state.frameTimes.push(performance.now()-start);if(state.frameTimes.length>1200)state.frameTimes.shift();if(!performance.getEntriesByName('archmap:first-frame').length)performance.mark('archmap:first-frame');if(moving())raf=requestAnimationFrame(frame);else last=0;}
function resize(){state.width=innerWidth;const r=scene.getBoundingClientRect();state.sheet=innerWidth<900&&!state.collapsed?r.height*.46:0;engine.resize(r.width,r.height);edges.resize(r.width,r.height);invalidate();}
function refresh(){ui.render();resize();}
$('zoom-in').onclick=()=>cameraTo({zoom:Math.min(3,state.camera.zoom*1.2)});$('zoom-out').onclick=()=>cameraTo({zoom:Math.max(.25,state.camera.zoom/1.2)});$('fit').onclick=()=>fitAll();
function focusRelated(id){if(!id){state.focusNodes=state.focusEdges=null;return}const nodes=new Set([id]);for(const direction of['from','to']){const queue=[id],seen=new Set(queue);while(queue.length){const cur=queue.shift();for(const e of model.edges.filter(e=>e[direction]===cur)){const other=e[direction==='from'?'to':'from'];if(!seen.has(other)){seen.add(other);nodes.add(other);queue.push(other)}}}}state.focusNodes=nodes;state.focusEdges=new Set(model.edges.filter(e=>nodes.has(e.from)&&nodes.has(e.to)).map(e=>e.id));}
function select(id){if(!model.nodes.some(n=>n.id===id))return;if(state.blast){const ids=new Set(state.blastState.offline);ids.has(id)?ids.delete(id):ids.add(id);state.blastState=blast(model,[...ids]);state.selected=id;refresh();return}state.selected=id;state.payload=null;state.tour=-1;state.trace=null;state.collapsed=false;focusRelated(id);refresh();save();}
function clearSelection(){state.selected=state.payload=null;state.trace=null;state.tour=-1;focusRelated(null);refresh();}
function setBlast(ids){state.blast=!!ids;if(Array.isArray(ids))state.blastState=blast(model,ids);else if(!ids)state.blastState=blast(model);state.selected=null;state.payload=null;state.tour=-1;state.trace=null;focusRelated(null);state.collapsed=false;refresh();}
function fitAll(){state.baseZoom=innerWidth<=600?.7:1;cameraTo({panX:0,panZ:0,zoom:state.baseZoom});}
function reset(){state.blast=false;state.blastState=blast(model);state.selected=state.payload=state.trace=null;state.tour=-1;state.rotate=false;focusRelated(null);state.baseZoom=innerWidth<=600?.7:1;cameraTo(initialCamera());refresh();}
function setPlan(value=!state.camera.plan){cameraTo({plan:value,pitch:value?Math.PI/2:61*Math.PI/180,yaw:value?0:-5*Math.PI/180});refresh();}
function frameNodes(ids){const ns=model.nodes.filter(n=>ids.includes(n.id));if(!ns.length)return;const b=model.layout.bounds;const x=(Math.min(...ns.map(n=>n.position.x))+Math.max(...ns.map(n=>n.position.x)))/2,z=(Math.min(...ns.map(n=>n.position.z))+Math.max(...ns.map(n=>n.position.z)))/2;const span=Math.max(850,Math.max(...ns.map(n=>n.position.x))-Math.min(...ns.map(n=>n.position.x))+400,Math.max(...ns.map(n=>n.position.z))-Math.min(...ns.map(n=>n.position.z))+400);cameraTo({panX:x-(b.x0+b.x1)/2,panZ:z-(b.z0+b.z1)/2,zoom:Math.min(2.2,Math.max(1,Math.min(b.x1-b.x0,b.z1-b.z0)/span))});}
function tour(index){state.tour=(index+model.tour.length)%model.tour.length;const t=model.tour[state.tour];state.selected=state.payload=state.trace=null;state.blast=false;state.blastState=blast(model);state.focusNodes=new Set(t.focus);state.focusEdges=new Set(t.edges);state.collapsed=false;refresh();frameNodes(t.focus);}
function step(dir=1){tour(state.tour<0?(dir>0?0:model.tour.length-1):state.tour+dir);}
function payload(id){state.selected=null;state.tour=-1;state.payload=id;state.collapsed=false;state.focusEdges=new Set(model.edges.filter(e=>e.payload===id).map(e=>e.id));state.focusNodes=new Set(model.edges.filter(e=>e.payload===id).flatMap(e=>[e.from,e.to]));refresh();}
function traceGate(){if(!state.selected)return;state.trace=trace(model,state.selected,[...state.blastState.offline,...state.blastState.starved]);state.focusNodes=new Set(state.trace.nodes);state.focusEdges=new Set(state.trace.edges);refresh();frameNodes(state.trace.nodes);}
function applyPatch(patch){if(!patch.model)return;const next=JSON.parse(JSON.stringify(patch.model));const old=model,camera={...state.camera},at=performance.now();for(const n of next.nodes){const prev=old.nodes.find(x=>x.id===n.id);if(prev&&prev.height!==n.height){heightTweens[n.id]={from:state.heights[n.id]??prev.height,to:n.height,at,duration:state.reduced?0:400};state.heights[n.id]=prev.height;state.pulses[n.id]=at+4000;}if(prev&&prev.maturity!==n.maturity){state.tags[n.id]={text:prev.maturity+' → '+n.maturity,until:at+4000};state.pulses[n.id]=at+4000;}if(prev&&(prev.position.x!==n.position.x||prev.position.z!==n.position.z)&&!state.reduced){positionTweens[n.id]={from:{...prev.position},to:{...n.position},at};n.position={...n.position,x:prev.position.x,z:prev.position.z};}}
 for(const c of next.checks){const prev=old.checks.find(x=>x.id===c.id);if(prev&&(prev.status!==c.status||prev.passed!==c.passed||prev.errored!==c.errored)){const bound=next.nodes.filter(n=>n.checks.includes(c.id)).map(n=>n.id);for(const e of next.edges)if(bound.includes(e.from)||bound.includes(e.to))state.edgeFlashes[e.id]=at+4000;}}
 const removedNodes=renderModel.nodes.filter(n=>!next.nodes.some(x=>x.id===n.id)),removedEdges=renderModel.edges.filter(e=>!next.edges.some(x=>x.id===e.id));
 if(!state.reduced){for(const group of['nodes','edges'])for(const item of next[group])if(!old[group].some(x=>x.id===item.id)){delete state.heights[item.id];state.opacity[item.id]=0;opacityTweens[item.id]={from:0,to:1,at};}for(const item of[...removedNodes,...removedEdges])if(!opacityTweens[item.id])opacityTweens[item.id]={from:state.opacity[item.id]??1,to:0,at};}
 model=next;renderModel=state.reduced?model:{...model,nodes:[...model.nodes,...removedNodes],edges:[...model.edges,...removedEdges]};engine.update(renderModel);labels.sync(renderModel);state.camera=camera;state.blastState=blast(model,state.blastState.offline.filter(id=>model.nodes.some(n=>n.id===id)));for(const change of patch.changes||[]){if(['model.meta','node.height','node.position','check.ranAt','zone.plate','model.layout'].includes(change.op))continue;const n=model.nodes.find(n=>n.id===change.id),title=n?.title||change.id||'Repository';let text=change.op==='node.metric'?`${title}: ${change.from?.value??change.from} → ${change.to?.value??change.to} non-blank lines`:change.op==='node.maturity'?`${title}: ${change.from} → ${change.to}`:`${title}: ${change.op.replaceAll('.',' ')} changed`;if(change.op.startsWith('check.')){const c=model.checks.find(c=>c.id===change.id);text=`${change.id}: ${c?.status||'removed'}${c?.collected!==null&&c?.collected!==undefined?` · ${c.passed} passed / ${c.collected} collected`:''}`;}state.changes.unshift({at:patch.at||model.meta.generated,node:n?.id,text,trigger:patch.trigger||[],source:n?.sources?.[0]});}if(!(patch.changes||[]).length&&patch.trigger?.length)state.changes.unshift({at:patch.at,node:null,text:'Repository sources refreshed',trigger:patch.trigger});state.changes=state.changes.slice(0,200);refresh();ui.announce('Architecture updated. '+(patch.trigger||[]).join(', '));setTimeout(invalidate,4050);}
const ui=new UI(()=>({model,state}),{select,payload,step,tour,trace:traceGate,frame:frameNodes,tab:name=>{state.tab=name;ui.render();save();}});
$('flow').onclick=()=>{state.flow=!state.flow;ui.render();invalidate()};$('step').onclick=()=>step();$('reset').onclick=reset;$('blast').onclick=()=>setBlast(state.blast?false:[]);$('search').onclick=()=>ui.openPalette();$('plan').onclick=()=>setPlan();$('rotate').onclick=()=>{if(state.reduced)return;state.rotate=!state.rotate;if(state.rotate){state.camera.plan=false;state.camera.pitch=61*Math.PI/180}ui.render();invalidate()};$('panel-toggle').onclick=()=>{state.collapsed=!state.collapsed;refresh();save()};$('outline-toggle').onclick=()=>ui.toggleDrawer('outline');$('changes').onclick=()=>ui.toggleDrawer('changes-drawer');$('legend-toggle').onclick=()=>{const el=$('legend-body');el.hidden=!el.hidden;$('legend-toggle').setAttribute('aria-expanded',!el.hidden);invalidate()};
$('labels').addEventListener('click',e=>{const id=e.target.closest('[data-edge]')?.dataset.edge;if(id)payload(model.edges.find(e=>e.id===id).payload)});
$('labels').addEventListener('pointermove',e=>{const id=e.target.closest('[data-node]')?.dataset.node;if(id){const r=scene.getBoundingClientRect();if(state.hover!==id){state.hoverEdge=null;if(state.hover)liftTweens[state.hover]={from:state.lifts[state.hover]||0,to:0,at:performance.now(),duration:state.reduced?0:180};state.hover=id;liftTweens[id]={from:state.lifts[id]||0,to:state.reduced?0:5,at:performance.now(),duration:state.reduced?0:180};invalidate()}ui.hover(id,e.clientX-r.left,e.clientY-r.top)}});$('labels').addEventListener('pointerleave',()=>{ui.hover(null);if(state.hover){liftTweens[state.hover]={from:state.lifts[state.hover]||0,to:0,at:performance.now(),duration:state.reduced?0:180};state.hover=null;invalidate()}});
function stopRotate(){if(state.rotate){state.rotate=false;ui.render();invalidate()}}
for(const ev of['pointerdown','wheel','keydown'])document.addEventListener(ev,e=>{if(ev!=='pointerdown'||!e.target.closest?.('#rotate'))stopRotate()},{capture:true,passive:true});
const pointers=new Map();let drag=null,pinch=null;
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});tween=null;if(pointers.size===2){const[a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:state.camera.zoom};drag=null;return}drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.shiftKey||e.button===1||e.button===2,moved:false};});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(pointers.has(e.pointerId))pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pinch&&pointers.size===2){const[a,b]=[...pointers.values()];state.camera.zoom=Math.max(.25,Math.min(3,pinch.zoom*Math.hypot(a.x-b.x,a.y-b.y)/pinch.distance));invalidate();return}if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4;if(drag.pan){const yaw=state.camera.yaw,scale=engine.scale;state.camera.panX-=(dx*Math.cos(yaw)+dy*Math.sin(yaw))/scale;state.camera.panZ-=(-dx*Math.sin(yaw)+dy*Math.cos(yaw))/scale;}else{state.camera.plan=false;state.camera.yaw=Math.max(-Math.PI/3,Math.min(Math.PI/3,state.camera.yaw-dx*.004));state.camera.pitch=Math.max(20*Math.PI/180,Math.min(89*Math.PI/180,state.camera.pitch+dy*.004));}drag.x=e.clientX;drag.y=e.clientY;ui.hover(null);invalidate();return}const id=engine.pick(x,y),edge=id?null:edges.pick(x,y);if(edge!==state.hoverEdge){state.hoverEdge=edge;invalidate()}canvas.style.cursor=id||edge?'pointer':'grab';if(id!==state.hover){const now=performance.now();if(state.hover)liftTweens[state.hover]={from:state.lifts[state.hover]||0,to:0,at:now,duration:state.reduced?0:180};state.hover=id;if(id)liftTweens[id]={from:state.lifts[id]||0,to:state.reduced?0:3,at:now,duration:state.reduced?0:180};invalidate()}if(edge)ui.edgeHover(edge,x,y);else ui.hover(id,x,y);});
canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(pinch){if(pointers.size<2)pinch=null;drag=null;return}if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,id=engine.pick(x,y),edge=edges.pick(x,y);if(id)select(id);else if(edge)payload(model.edges.find(e=>e.id===edge).payload);else clearSelection()}drag=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=pinch=null});canvas.addEventListener('pointerleave',()=>{if(!drag){ui.hover(null);if(state.hoverEdge){state.hoverEdge=null;invalidate()}if(state.hover){liftTweens[state.hover]={from:state.lifts[state.hover]||0,to:0,at:performance.now(),duration:state.reduced?0:180};state.hover=null;invalidate()}}});
canvas.addEventListener('dblclick',e=>{const r=canvas.getBoundingClientRect(),id=engine.pick(e.clientX-r.left,e.clientY-r.top);if(id)frameNodes([id]);});
canvas.addEventListener('wheel',e=>{e.preventDefault();tween=null;const r=canvas.getBoundingClientRect(),old=state.camera.zoom,next=Math.max(.25,Math.min(3,old*Math.exp(-e.deltaY*.001)));const x=(e.clientX-r.left-r.width/2)/engine.scale,z=(e.clientY-r.top-r.height/2)/engine.scale,ratio=1-old/next,yaw=state.camera.yaw;state.camera.panX+=(x*Math.cos(yaw)+z*Math.sin(yaw))*ratio;state.camera.panZ+=(-x*Math.sin(yaw)+z*Math.cos(yaw))*ratio;state.camera.zoom=next;invalidate()},{passive:false});
let keyboardIndex=-1;document.addEventListener('keydown',e=>{const input=e.target.closest('input,textarea,[contenteditable]');if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();ui.openPalette();return}if(input)return;const k=e.key.toLowerCase();if(k==='escape'){if(!$('palette').hidden)ui.closePalette();else if(!$('outline').hidden)ui.close('outline');else if(!$('changes-drawer').hidden)ui.close('changes-drawer');else if(state.blast)setBlast(false);else clearSelection();return}if(k==='tab'&&e.target===canvas){const ns=[...model.nodes].sort((a,b)=>a.position.rank-b.position.rank||a.position.x-b.position.x||a.id.localeCompare(b.id));const next=keyboardIndex+(e.shiftKey?-1:1);if(next<0||next>=ns.length){keyboardIndex=-1;return}e.preventDefault();keyboardIndex=next;state.keyboardNode=ns[next].id;$('announcer').textContent=ns[next].title+'. '+ns[next].maturity+'. Press Enter for evidence.';state.pulses[ns[next].id]=performance.now()+4000;invalidate();return}if(k==='enter'&&e.target===canvas&&state.keyboardNode){select(state.keyboardNode);return}if(k===' '&&!e.target.closest('button,a,[role=tab]')){e.preventDefault();$('flow').click()}else if(['arrowleft','arrowright'].includes(k)&&!e.target.closest('[role=tab]')){e.preventDefault();step(k==='arrowright'?1:-1)}else if(k==='r')reset();else if(k==='b')setBlast(state.blast?false:[]);else if(k==='/'){e.preventDefault();ui.openPalette()}else if(k==='p')setPlan();else if(k==='o')ui.toggleDrawer('outline');else if(k==='c'&&state.live!=='snapshot')ui.toggleDrawer('changes-drawer');else if(/^[1-9]$/.test(k)){const tier=model.tiers.find(t=>t.order===Number(k));if(tier)frameNodes(model.nodes.filter(n=>n.tier===tier.id).map(n=>n.id));}});
function minimap(){const el=$('minimap'),b=model.layout.bounds,ctx=el.getContext('2d'),w=168,h=124,pad=10,scale=Math.min((w-2*pad)/(b.x1-b.x0),(h-2*pad)/(b.z1-b.z0));const xy=(x,z)=>[pad+(x-b.x0)*scale,pad+(z-b.z0)*scale];minimapBounds={scale,pad,b};const box={x0:engine.width-184,y0:engine.height-222,x1:engine.width-16,y1:engine.height-98};el.hidden=model.nodes.some(n=>{const p=engine.project(n.position.x,n.height,n.position.z);return p[0]>box.x0-10&&p[0]<box.x1+10&&p[1]>box.y0-10&&p[1]<box.y1+10});ctx.clearRect(0,0,w,h);ctx.fillStyle='#ECEEE3';ctx.strokeStyle='#C3CABA';for(const z of model.zones){const p=z.plate,a=xy(p.x0,p.z0);ctx.fillRect(...a,(p.x1-p.x0)*scale,(p.z1-p.z0)*scale)}ctx.fillStyle='#526444';for(const n of model.nodes){const p=xy(n.position.x,n.position.z);ctx.fillRect(p[0]-1,p[1]-1,3,3)}const c=state.camera,cx=(b.x0+b.x1)/2+c.panX,cz=(b.z0+b.z1)/2+c.panZ,ww=engine.width/engine.scale,hh=engine.height/engine.scale/Math.sin(c.pitch);ctx.strokeStyle='#526444';ctx.beginPath();[[-1,-1],[1,-1],[1,1],[-1,1]].forEach(([x,z],i)=>{const xx=x*ww/2,zz=z*hh/2,p=xy(cx+xx*Math.cos(c.yaw)+zz*Math.sin(c.yaw),cz-xx*Math.sin(c.yaw)+zz*Math.cos(c.yaw));i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.closePath();ctx.stroke();$('scale').querySelector('i').style.width=Math.max(15,150*engine.scale)+'px';}
$('minimap').onclick=e=>{if(!minimapBounds)return;const r=e.target.getBoundingClientRect(),{b,pad,scale}=minimapBounds;cameraTo({panX:(e.clientX-r.left-pad)/scale+b.x0-(b.x0+b.x1)/2,panZ:(e.clientY-r.top-pad)/scale+b.z0-(b.z0+b.z1)/2});};
function frozen(value){if(value&&typeof value==='object'){Object.freeze(value);Object.values(value).forEach(frozen)}return value}Object.defineProperty(window,'__ARCHMAP',{value:Object.freeze({get state(){return frozen(JSON.parse(JSON.stringify({...state,focusNodes:state.focusNodes?[...state.focusNodes]:null,focusEdges:state.focusEdges?[...state.focusEdges]:null,engine:engine.kind,cameraMatrix:engine.matrix(),labels:labels.visible,blockedLabels:labels.blocked,zoneLabels:labels.zones,particleCount:edges.markers.length,particles:edges.markers,model})))},select,step,reset,setBlast,setPlan,fitAll,applyPatch}),writable:false});
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;last=0}else invalidate()});reduced.addEventListener('change',()=>{state.reduced=reduced.matches;if(state.reduced){state.rotate=false;if(tween){Object.assign(state.camera,tween.to);tween=null}}refresh()});
refresh();cancelAnimationFrame(raf);raf=0;frame(performance.now());document.fonts.ready.then(invalidate);
// Paint a usable board immediately; initialize the GPU after the first presentation.
// Cold GPU startup can otherwise block the first visible frame for over a second.
requestAnimationFrame(()=>requestAnimationFrame(()=>{const gpuCanvas=document.createElement('canvas');gpuCanvas.id='board3d';gpuCanvas.setAttribute('aria-hidden','true');scene.insertBefore(gpuCanvas,canvas);let gpu=null;try{gpu=create3D(gpuCanvas,model)}catch{}if(gpu){engine.dispose();engine=gpu;canvas.getContext('2d').clearRect(0,0,canvas.width,canvas.height);canvas.style.background='transparent';}else{gpuCanvas.remove();state.camera.plan=true;state.camera.pitch=Math.PI/2;}refresh();}));
connectLive({get:()=>({model,state}),applyPatch,refresh,ui});
