const {chromium}=require(process.env.ARCHMAP_PLAYWRIGHT||'../../.artifacts/test-runtime/node_modules/playwright');
const {spawn,spawnSync}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../../../..'),art=path.join(root,'tools/archmap/.artifacts'),copy=path.join(art,'live-repo');
const exe=process.env.ARCHMAP_CHROMIUM||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const wait=ms=>new Promise(r=>setTimeout(r,ms));let server,browser,port,url;
async function start(reuse){return new Promise((resolve,reject)=>{server=spawn('python3',['tools/archmap/serve.py','--root',copy,'--port',String(reuse||0)],{cwd:root,env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});let out='';server.stdout.on('data',b=>{out+=b.toString();if(out.includes('\n')){try{const data=JSON.parse(out.split('\n')[0]);url=data.url;port=Number(new URL(url).port);resolve()}catch(e){reject(e)}}});server.stderr.on('data',b=>process.stderr.write(b));server.on('error',reject);server.on('exit',code=>{if(!url)reject(Error('Server exit '+code))});})}
async function stop(){if(server&&!server.killed){server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));}}
async function state(p){return p.evaluate(()=>__ARCHMAP.state)}
(async()=>{assert.equal(spawnSync('python3',['tools/archmap/tests/e2e/copy_repo.py'],{cwd:root,stdio:'inherit'}).status,0);await start();browser=await chromium.launch({executablePath:exe,headless:process.env.ARCHMAP_HEADLESS==='1'});const p=await browser.newPage({viewport:{width:1440,height:900}}),pageErrors=[];p.on('pageerror',e=>pageErrors.push(e.message));await p.goto(url);await p.waitForFunction(()=>window.__ARCHMAP?.state.live==='live');await wait(800);for(const width of[1440,1280,1180,1100,1024,960,900]){await p.setViewportSize({width,height:900});const g=await p.evaluate(()=>{const h=document.querySelector('h1'),r=document.createRange();r.selectNodeContents(h);return{titleRight:r.getBoundingClientRect().right,controlsLeft:document.getElementById('controls').getBoundingClientRect().left,scroll:document.documentElement.scrollWidth>innerWidth}});assert.ok(g.titleRight<=g.controlsLeft&&!g.scroll,JSON.stringify({width,g}))}await p.setViewportSize({width:1440,height:900});console.log('PASS live header breakpoints');const scan=await p.locator('#sync-status').getAttribute('title'),stable=await state(p);await p.waitForFunction(t=>document.getElementById('sync-status').title!==t,scan,{timeout:6500});assert.equal((await state(p)).model.meta.rev,stable.model.meta.rev);assert.deepEqual((await state(p)).cameraMatrix,stable.cameraMatrix);assert.ok((await p.locator('#sync-label').innerText()).includes('up to date'));console.log('PASS live scan heartbeat without revision or camera change');await p.evaluate(()=>__ARCHMAP.select('hellostats'));await p.locator('#tab-how').click();await wait(80);await p.evaluate(()=>{document.getElementById('inspector').scrollTop=160;document.getElementById('how').scrollTop=75});const before=await state(p),scroll=await p.locator('#inspector').evaluate(e=>e.scrollTop),file=path.join(copy,'projects/hello-stats/src/main.rs'),started=Date.now();fs.appendFileSync(file,Array.from({length:20},(_,i)=>'// archmap isolated fixture '+i).join('\n')+'\n');await p.waitForFunction(rev=>__ARCHMAP.state.model.meta.rev>rev,before.model.meta.rev,{timeout:2000});const observed=Date.now()-started;await p.screenshot({path:path.join(art,'live-mid-animation.png')});const mid=await state(p);assert.equal(mid.selected,'hellostats');assert.equal(mid.tab,'how');assert.deepEqual(mid.cameraMatrix,before.cameraMatrix);assert.equal(await p.locator('#inspector').evaluate(e=>e.scrollTop),scroll);assert.ok(mid.changes.some(c=>c.trigger.includes('projects/hello-stats/src/main.rs')));await wait(500);const after=await state(p),n=after.model.nodes.find(n=>n.id==='hellostats'),old=before.model.nodes.find(n=>n.id==='hellostats');assert.equal(n.metric.value,old.metric.value+20);assert.ok(after.heights.hellostats>old.height);assert.deepEqual(after.model.nodes.map(n=>n.position),before.model.nodes.map(n=>n.position));console.log('PASS live edit',observed+'ms');
const date='2000-01-01',pair=null; // Synthetic structure only; the public projection contains no private identities.
// Synthetic unverified test fixture. It expressly claims no command or artifact evidence.
const receipt={schema_version:'phase0-proof.v1',reset_id:'synthetic-reset',date,pair_slice_id:pair,artifact_paths:[],command_results:[],observed_output_digest:null,test_count:0,changed_paths:[],verdict:'unverified',blocker:'Isolated architecture-map test fixture; no implementation evidence',course_resume_point:null,next_command:'python3 --version',evidence_basis:{artifacts_observed:false,commands_observed:false,schedule_only:false,task_state_only:false}};
fs.writeFileSync(path.join(copy,'progress/proofs/archmap-valid-fixture.json'),JSON.stringify(receipt,null,2));await p.waitForFunction(()=>__ARCHMAP.state.model.receiptContracts.some(r=>r.path.endsWith('archmap-valid-fixture.json')),{},{timeout:2500});let s=await state(p);assert.equal(s.model.receiptContracts[0].status,'UNAVAILABLE');assert.ok(await p.locator('.receipt-verdict').innerText().then(t=>t.includes('UNAVAILABLE')));fs.writeFileSync(path.join(copy,'progress/proofs/archmap-malformed-fixture.json'),JSON.stringify({schema_version:'wrong'}));await p.waitForFunction(()=>__ARCHMAP.state.model.receiptContracts.length===2,{},{timeout:2500});s=await state(p);const invalid=s.model.receiptContracts.find(r=>r.path.includes('malformed'));assert.equal(invalid.status,'FAIL');assert.ok(invalid.errors[0].startsWith('proof missing fields:'));assert.ok((await p.locator('.receipt-verdict').innerText()).includes('FAIL'));
const direct=spawnSync('python3',['-c',`import sys,json;sys.dont_write_bytecode=True;sys.path.insert(0,'tools/archmap');import checks;print(json.dumps(checks.receipt_contracts(${JSON.stringify(copy)})))`],{cwd:root,encoding:'utf8'});assert.equal(direct.status,0);assert.deepEqual(s.model.receiptContracts,JSON.parse(direct.stdout));console.log('PASS receipt preflight never claims private validation');
const checkStamp=s.model.checks.find(c=>c.id==='unit-beginner').ranAt;await p.waitForFunction(stamp=>__ARCHMAP.state.model.checks.find(c=>c.id==='unit-beginner').ranAt!==stamp,checkStamp,{timeout:6000});const checked=await state(p);assert.equal(checked.model.checks.find(c=>c.id==='unit-beginner').passed,7);console.log('PASS automatic checks');
const noToken=await fetch(url+'/api/run-checks',{method:'POST'});assert.equal(noToken.status,403);const badHost=await new Promise((resolve,reject)=>{const r=require('node:http').get(url+'/api/model',{headers:{Host:'malicious.invalid'}},res=>{res.resume();resolve(res.statusCode)});r.on('error',reject)});assert.equal(badHost,403);console.log('PASS HTTP guards');
await p.locator('#search').click();await p.locator('#query').fill('receipt');await stop();await p.waitForFunction(()=>__ARCHMAP.state.live==='reconnecting',{},{timeout:2500});assert.equal(await p.locator('#query').inputValue(),'receipt');assert.equal((await state(p)).selected,'hellostats');fs.appendFileSync(file,'// change while disconnected\n');await start(port);await p.waitForFunction(()=>__ARCHMAP.state.live==='live',{},{timeout:12000});assert.equal((await state(p)).model.nodes.find(n=>n.id==='hellostats').metric.value,old.metric.value+21);assert.equal(await p.locator('#query').inputValue(),'receipt');assert.deepEqual(pageErrors,[]);console.log('PASS reconnect and preserved palette');
fs.writeFileSync(path.join(art,'live-report.json'),JSON.stringify({status:'PASS',editObservedMs:observed,receiptContracts:s.model.receiptContracts,automaticChecks:checked.model.checks,guards:{noToken:403,badHost:403},reconnect:true,pageErrors},null,2));await browser.close();await stop();})().catch(async e=>{console.error(e);await browser?.close();await stop();process.exitCode=1});
