// Optional browser harness; production devDependencies remain three + esbuild only.
const {chromium}=require(process.env.ARCHMAP_PLAYWRIGHT||'../../.artifacts/test-runtime/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),os=require('node:os');
const root=path.resolve(__dirname,'../../../..'),art=path.join(root,'tools/archmap/.artifacts');
const executable=process.env.ARCHMAP_CHROMIUM||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const headless=process.env.ARCHMAP_HEADLESS==='1';
const results=[];let browser;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function independentBlast(m,offline){const dead=new Set(offline),starved=new Set(),es=m.edges.filter(e=>!e.blocked&&!e.feedback);for(let round=0;round<m.nodes.length;round++)for(const n of m.nodes){if(dead.has(n.id))continue;const ins=es.filter(e=>e.to===n.id);if(!ins.length)continue;const kinds=['data','control'];const primary=kinds.map(k=>ins.filter(e=>e.kind===k)).find(a=>a.length)||ins;if(primary.every(e=>dead.has(e.from))){dead.add(n.id);starved.add(n.id)}}return[...starved].sort();}
async function test(name,fn){try{const evidence=await fn();results.push({name,status:'PASS',evidence});console.log('PASS',name,evidence||'')}catch(e){results.push({name,status:'FAIL',error:e.message});console.error('FAIL',name,e.stack);}}
async function ready(page){await page.goto('file://'+path.join(root,'docs/architecture/index.html'));await page.waitForFunction(()=>window.__ARCHMAP);await page.waitForTimeout(650);}
async function state(page){return page.evaluate(()=>__ARCHMAP.state)}
function intersect(a,b){return a.x0<b.x1&&a.x1>b.x0&&a.y0<b.y1&&a.y1>b.y0}
(async()=>{fs.mkdirSync(art,{recursive:true});browser=await chromium.launch({executablePath:executable,headless});
for(const[width,height]of[[1440,900],[1024,700],[390,844]])await test('offline '+width,async()=>{const p=await browser.newPage({viewport:{width,height}}),errors=[],requests=[];p.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.text())});p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!/^(file:|data:)/.test(r.url()))requests.push(r.url())});await ready(p);const s=await state(p);assert.equal(s.model.nodes.length,34);assert.equal(s.blockedLabels.length,4);if(width===1440)assert.equal(s.labels.length,34);if(width===1024)assert.ok(s.labels.length>=31);for(const n of s.model.nodes){assert.ok(n.sources.length);assert.ok(['planned','stub','implemented','tested','deployed'].includes(n.maturity));if(n.external)assert.ok(n.inferred)}const boxes=[...s.labels,...s.blockedLabels,...s.zoneLabels];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++)assert.ok(!intersect(boxes[i],boxes[j]),`overlap ${boxes[i].id} ${boxes[j].id}`);const geom=await p.evaluate(()=>({scroll:document.documentElement.scrollWidth>innerWidth,first:performance.getEntriesByName('archmap:first-frame')[0].startTime,hud:[...document.querySelectorAll('#scene .hud')].filter(e=>!e.hidden&&getComputedStyle(e).display!=='none').map(e=>{let r=e.getBoundingClientRect(),s=document.getElementById('scene').getBoundingClientRect();return{x0:r.left-s.left,y0:r.top-s.top,x1:r.right-s.left,y1:r.bottom-s.top}})}));assert.ok(!geom.scroll);for(const b of boxes)for(const h of geom.hud)assert.ok(!intersect(b,h),'HUD collision '+b.id);assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);assert.ok(geom.first<=300,'first frame '+geom.first);assert.equal(s.particleCount,150);await p.screenshot({path:path.join(art,`fit-${width}.png`)});await p.close();return{labels:s.labels.length,blocked:s.blockedLabels.length,engine:s.engine,firstFrame:geom.first}});
const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.text())});p.on('pageerror',e=>errors.push(e.message));await ready(p);
await test('visible numbers trace to the model',async()=>{const unknown=await p.evaluate(()=>{const m=__ARCHMAP.state.model,known=new Set((JSON.stringify(m).match(/\d+/g)||[]));for(const k of['planned','stub','implemented','tested','deployed'])known.add(String(m.nodes.filter(n=>n.maturity===k).length));known.add(String(m.nodes.filter(n=>['implemented','tested','deployed'].includes(n.maturity)&&!n.inferred).length));const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),unknown=[];let node;while(node=walker.nextNode()){const el=node.parentElement;if(!el||['SCRIPT','STYLE'].includes(el.tagName)||el.closest('[hidden]')||!el.getClientRects().length||el.closest('.metadata .optional'))continue;for(const n of node.textContent.match(/\d+/g)||[])if(!known.has(n))unknown.push({number:n,text:node.textContent})}return unknown});assert.deepEqual(unknown,[]);});
await test('header breakpoints',async()=>{for(const width of[1440,1280,1180,1100,1024,960,900]){await p.setViewportSize({width,height:900});const g=await p.evaluate(()=>{const a=document.querySelector('.brand').getBoundingClientRect(),b=document.getElementById('controls').getBoundingClientRect(),h=document.querySelector('h1'),range=document.createRange();range.selectNodeContents(h);return{overlap:a.right>b.left,overflow:document.documentElement.scrollWidth>innerWidth,clipped:range.getBoundingClientRect().right>b.left}});assert.ok(!g.overlap&&!g.overflow&&!g.clipped,JSON.stringify({width,g}))}await p.setViewportSize({width:1440,height:900});});
await test('exact labels and flow',async()=>{for(const[id,label]of Object.entries({flow:'Pause the flow',step:'Trace one step',reset:'Reset view',blast:'Blast radius',plan:'Plan view',rotate:'Rotate','tab-what':'What it does','tab-how':"How it's built"}))assert.equal(await p.locator('#'+id).innerText(),label);await p.locator('#board').focus();await p.keyboard.press('Space');await delay(80);let a=await state(p);await delay(150);let b=await state(p);assert.equal(a.flowTime,b.flowTime);assert.equal(a.frameCount,b.frameCount,'static paused must not render');await p.keyboard.press('Space');await delay(150);assert.ok((await state(p)).flowTime>b.flowTime);});
await test('tour and reset',async()=>{await p.locator('#board').focus();for(let i=0;i<8;i++){await p.keyboard.press('ArrowRight');await delay(550);assert.equal((await state(p)).tour,i);if(i===5)await p.screenshot({path:path.join(art,'tour-6.png')})}assert.ok((await p.locator('#inspector').innerText()).includes('The gate is starved'));await p.keyboard.press('ArrowLeft');assert.equal((await state(p)).tour,6);await p.keyboard.press('r');await delay(550);const s=await state(p);assert.equal(s.tour,-1);assert.equal(s.camera.zoom,1);assert.ok(Math.abs(s.camera.yaw+5*Math.PI/180)<1e-6);});
await test('canvas keyboard and hover evidence',async()=>{await p.locator('#board').focus();await p.keyboard.press('Tab');assert.ok((await state(p)).keyboardNode);const id=(await state(p)).keyboardNode;await p.keyboard.press('Enter');assert.equal((await state(p)).selected,id);await p.evaluate(()=>__ARCHMAP.reset());await delay(550);await p.locator('#labels [data-node="receipts"]').hover();assert.ok(await p.locator('#hover').isVisible());assert.ok((await p.locator('#hover').innerText()).includes('Non-blank'));await p.mouse.move(1,1);});
await test('orbit pan zoom plan rotate',async()=>{await p.mouse.move(120,180);await p.mouse.down();await p.mouse.move(180,210,{steps:5});await p.mouse.up();let s=await state(p);assert.notEqual(s.camera.yaw,-5*Math.PI/180);const yaw=s.camera.yaw;await p.keyboard.down('Shift');await p.mouse.move(120,180);await p.mouse.down();await p.mouse.move(160,230,{steps:5});await p.mouse.up();await p.keyboard.up('Shift');s=await state(p);assert.equal(s.camera.yaw,yaw);assert.notEqual(s.camera.panX,0);await p.mouse.wheel(0,-10000);await delay(100);assert.equal((await state(p)).camera.zoom,3);await p.mouse.wheel(0,10000);await delay(100);assert.equal((await state(p)).camera.zoom,.25);await p.locator('#reset').click();await delay(550);await p.locator('#plan').click();await delay(550);s=await state(p);assert.equal(s.camera.pitch,Math.PI/2);assert.equal(s.camera.plan,true);await p.screenshot({path:path.join(art,'plan.png')});await p.locator('#rotate').click();await delay(300);s=await state(p);assert.ok(s.rotate);const before=s.camera.yaw;await delay(100);assert.notEqual((await state(p)).camera.yaw,before);await p.keyboard.press('Shift');assert.equal((await state(p)).rotate,false);});
await test('blast search outline panels',async()=>{await p.evaluate(()=>__ARCHMAP.setBlast(['receipts']));let s=await state(p);assert.deepEqual(s.blastState.starved,independentBlast(s.model,['receipts']));const spofs=s.model.nodes.filter(n=>n.id!=='gate'&&independentBlast(s.model,[n.id]).includes('gate')).map(n=>n.id).sort();assert.deepEqual([...s.model.spofs].sort(),spofs);await p.screenshot({path:path.join(art,'blast-receipts.png')});await p.keyboard.press('Escape');await p.locator('#search').click();await p.locator('#query').fill('receipt');assert.equal(await p.locator('#results .name').first().innerText(),'Proof receipts');await p.keyboard.press('ArrowDown');assert.equal(await p.locator('#query').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('ArrowUp');await p.keyboard.press('Enter');assert.equal((await state(p)).selected,'receipts');await p.locator('#trace-gate').click();assert.ok((await p.locator('.trace-result').innerText()).includes('planned'));await p.locator('#outline-toggle').click();assert.equal(await p.locator('#outline .node-choice').count(),34);await p.screenshot({path:path.join(art,'outline.png')});await p.locator('#outline [data-node="hellostats"]').click();assert.equal((await state(p)).selected,'hellostats');await p.locator('[data-close="outline"]').click();const words=(await p.locator('#what').innerText()).trim().split(/\s+/).length;assert.ok(words<=250,'words '+words);await p.locator('#tab-how').click();assert.equal(await p.locator('#how h3').last().innerText(),'Risks & open questions');});
await test('contrast and focus',async()=>{const result=await p.evaluate(()=>{const lum=s=>{const a=s.match(/[\d.]+/g).slice(0,3).map(Number).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*a[0]+.7152*a[1]+.0722*a[2]};const failures=[];for(const el of document.querySelectorAll('button,p,h1,h2,h3,.eyebrow,.chip,.node-meta,.source,code')){if(el.hidden||!el.getClientRects().length)continue;const cs=getComputedStyle(el);let bg=cs.backgroundColor,a=el;while(bg==='rgba(0, 0, 0, 0)'&&a.parentElement){a=a.parentElement;bg=getComputedStyle(a).backgroundColor}if(bg==='rgba(0, 0, 0, 0)')bg='rgb(245,242,235)';const x=lum(cs.color),y=lum(bg),ratio=(Math.max(x,y)+.05)/(Math.min(x,y)+.05);if(ratio<(parseFloat(cs.fontSize)>=24?3:4.5))failures.push({text:el.textContent.slice(0,45),color:cs.color,bg,ratio})}return failures});assert.deepEqual(result,[]);await p.locator('#board').focus();const ring=await p.locator('#board').evaluate(e=>getComputedStyle(e).outlineWidth);assert.equal(ring,'2px');});
await test('patch preserves UI and transitions topology',async()=>{await p.evaluate(()=>{__ARCHMAP.reset();__ARCHMAP.select('receipts')});await delay(550);await p.locator('#flow').click();await delay(80);const before=await state(p);await p.evaluate(()=>{const m=JSON.parse(JSON.stringify(__ARCHMAP.state.model));m.meta.rev++;m.edges=m.edges.filter(e=>e.id!=='x-cal-rcpt');m.layout.topology+='-test';__ARCHMAP.applyPatch({model:m,changes:[{op:'edge.remove',id:'x-cal-rcpt',from:{},to:null}],trigger:['isolated browser model'],at:m.meta.generated})});await delay(400);const after=await state(p);assert.equal(after.selected,'receipts');assert.deepEqual(after.cameraMatrix,before.cameraMatrix);assert.equal(after.model.edges.length,before.model.edges.length-1);assert.equal(after.opacity['x-cal-rcpt'],0);await p.evaluate(m=>__ARCHMAP.applyPatch({model:m,changes:[],trigger:[]}),before.model);await delay(400);assert.equal((await state(p)).opacity['x-cal-rcpt'],1);await p.locator('#flow').click();});
await test('zoom dock and connection interaction',async()=>{await p.evaluate(()=>__ARCHMAP.reset());await delay(550);const initial=(await state(p)).camera.zoom;await p.locator('#zoom-in').click();await delay(550);assert.ok((await state(p)).camera.zoom>initial);await p.locator('#zoom-out').click();await delay(550);assert.ok(Math.abs((await state(p)).camera.zoom-initial)<.001);await p.locator('#fit').click();await delay(550);assert.equal((await state(p)).camera.zoom,initial);await p.locator('#flow').click();const s=await state(p),scene=await p.locator('#board').boundingBox();let hit=null;for(const point of s.particles){if(point.y<75||point.y>scene.height-100)continue;await p.mouse.move(scene.x+point.x,scene.y+point.y);const current=await state(p);if(current.hoverEdge){hit=current.hoverEdge;break}}assert.ok(hit,'a visible connection can be hovered');assert.ok(await p.locator('#hover').isVisible());await p.mouse.down();await p.mouse.up();await delay(60);assert.ok((await state(p)).payload,'connection opens payload inspector');await p.mouse.move(0,0);await p.evaluate(()=>__ARCHMAP.reset());});
await test('performance 150 particles',async()=>{await p.evaluate(()=>__ARCHMAP.reset());await delay(650);const r=await p.evaluate(()=>new Promise(resolve=>{const deltas=[];let last,start;function tick(t){if(last)deltas.push(t-last);last=t;start??=t;if(t-start<5000)requestAnimationFrame(tick);else{deltas.sort((a,b)=>a-b);resolve({p95:deltas[Math.floor(deltas.length*.95)],frames:deltas.length,particles:__ARCHMAP.state.particleCount,engine:__ARCHMAP.state.engine})}}requestAnimationFrame(tick)}));assert.equal(r.particles,150);if(!headless)assert.ok(r.p95<=20,'p95 '+r.p95);return{...r,headed:!headless,machine:os.platform()+' '+os.arch()+' '+os.cpus()[0].model}});
await test('page health',async()=>assert.deepEqual(errors,[]));await p.close();
await test('reduced motion',async()=>{const p=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});await ready(p);const a=await state(p);await delay(200);const b=await state(p);assert.equal(a.flowTime,b.flowTime);assert.equal(a.frameCount,b.frameCount);await p.evaluate(()=>__ARCHMAP.setPlan(true));await delay(50);assert.equal((await state(p)).camera.pitch,Math.PI/2);assert.equal(await p.locator('#rotate').isDisabled(),true);await p.screenshot({path:path.join(art,'reduced-motion.png')});await p.close()});await browser.close();
await test('Canvas fallback',async()=>{const b=await chromium.launch({executablePath:executable,headless,args:['--disable-3d-apis']}),p=await b.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(['warning','error'].includes(m.type()))errors.push(m.text())});await ready(p);assert.equal((await state(p)).engine,'canvas2d');await p.evaluate(()=>__ARCHMAP.select('receipts'));assert.ok((await p.locator('#inspector').innerText()).includes('Proof receipts'));assert.deepEqual(errors,[]);await p.screenshot({path:path.join(art,'fallback.png')});await b.close()});
const output={at:new Date().toISOString(),results};fs.writeFileSync(path.join(art,'e2e-report.json'),JSON.stringify(output,null,2));console.log(results.filter(r=>r.status==='PASS').length+'/'+results.length+' passed');process.exitCode=results.some(r=>r.status==='FAIL')?1:0;
})().catch(async e=>{console.error(e);await browser?.close();process.exitCode=1});
